spring.application.name=mini-spotify

## CONFIGURACAO POSTGRES
spring.datasource.url=jdbc:postgresql://SEU_HOST_AQUI:22023/defaultdb?sslmode=require
spring.datasource.username=SEU_USUARIO_AQUI
spring.datasource.password=SUA_SENHA_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## CONFIGURACOES GERAIS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update